//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_GO2inkas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstanciaPago
    {
        public string NUMERO_DE_OPERACION { get; set; }
        public string factura { get; set; }
        public string VentaID { get; set; }
    
        public virtual Venta Venta { get; set; }
    }
}
