//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_GO2inkas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizacion()
        {
            this.Confirmacion = new HashSet<Confirmacion>();
        }
    
        public int NUMEROCOTIZACION { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string nombrecliente { get; set; }
        public string identificacion_del_cliente { get; set; }
        public string tipo_de_tour { get; set; }
        public Nullable<int> cantidad_de_pasajeros { get; set; }
        public string agregados { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<System.DateTime> fecha_de_tour { get; set; }
        public string tipo_de_bicicleta { get; set; }
        public Nullable<int> ClienteID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Confirmacion> Confirmacion { get; set; }
    }
}
