//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_GO2inkas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaSatisfaccion
    {
        public int IDENCUESTA { get; set; }
        public Nullable<int> facilidad_de_uso { get; set; }
        public Nullable<int> grado_de_satisfaccion { get; set; }
        public Nullable<int> ReservaID { get; set; }
    
        public virtual Reserva Reserva { get; set; }
    }
}
