//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_GO2inkas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int CODIGO { get; set; }
        public string ruta { get; set; }
        public Nullable<int> duracion { get; set; }
        public string dificultad { get; set; }
        public string tipo_de_bicicleta { get; set; }
        public Nullable<System.TimeSpan> tiempo { get; set; }
        public Nullable<System.DateTime> inicio { get; set; }
        public Nullable<System.DateTime> final { get; set; }
        public Nullable<decimal> precio { get; set; }
    }
}
