//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_GO2inkas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.ConstanciaPago = new HashSet<ConstanciaPago>();
            this.ReporteVenta = new HashSet<ReporteVenta>();
        }
    
        public string NUMERO_DE_OPERACION { get; set; }
        public string factura { get; set; }
        public string n_de_ruc { get; set; }
        public Nullable<System.DateTime> fecha_de_pago { get; set; }
        public string tipo_de_tour { get; set; }
        public Nullable<decimal> total { get; set; }
        public string nombre_de_cliente { get; set; }
        public string metodo_de_pago { get; set; }
        public string estado_de_venta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstanciaPago> ConstanciaPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteVenta> ReporteVenta { get; set; }
    }
}
